import 'dart:async';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:geoflutterfire_plus/geoflutterfire_plus.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../authentication/data/auth_repository.dart';
import '../../../core/services/location_service.dart';
import '../data/job_repository.dart';
import '../domain/job.dart';

final jobControllerProvider = NotifierProvider.autoDispose<JobController, AsyncValue<void>>(() {
  return JobController();
});

class JobController extends AutoDisposeNotifier<AsyncValue<void>> {
  @override
  AsyncValue<void> build() {
    return const AsyncData(null);
  }

  Future<void> postJob({
    required String title,
    required String description,
    required List<String> skills,
    required int wage,
    required int workersNeeded,
  }) async {
    final user = ref.read(authStateProvider).value;
    if (user == null) {
      state = AsyncError(Exception("Not authenticated"), StackTrace.current);
      return;
    }

    state = const AsyncLoading();
    try {
      final position = await ref.read(locationServiceProvider).getCurrentPosition();
      if (position == null) {
        state = AsyncError(Exception("Location permission is required to post a job"), StackTrace.current);
        return;
      }

      final geoPoint = GeoFirePoint(GeoPoint(position.latitude, position.longitude));

      final job = Job(
        id: '', // Generated by firestore
        contractorId: user.uid,
        title: title,
        description: description,
        skillsRequired: skills,
        wage: wage,
        workerCountNeeded: workersNeeded,
        geohash: geoPoint.geohash,
        location: geoPoint.geopoint,
      );
      await ref.read(jobRepositoryProvider).createJob(job);
      state = const AsyncData(null);
    } catch (e, st) {
      state = AsyncError(e, st);
    }
  }
}
