// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCLZSfvpt6II5GhX7LqWO-YCkA5WgzFKA',
    appId: '1:448205141152:web:901a5c35a67ca3b4e3c5c5',
    messagingSenderId: '448205141152',
    projectId: 'wrozo-5b147',
    authDomain: 'wrozo-5b147.firebaseapp.com',
    storageBucket: 'wrozo-5b147.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUO0faIvUoI-qbZedH8Wu1Lfh8CxvqlYc',
    appId: '1:448205141152:android:ef65a8aa23d0113fe3c5c5',
    messagingSenderId: '448205141152',
    projectId: 'wrozo-5b147',
    storageBucket: 'wrozo-5b147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzb6y29nD1FszKdzL3akbtLPZEf8DZ_o',
    appId: '1:448205141152:ios:f5625bf9bd7ced23e3c5c5',
    messagingSenderId: '448205141152',
    projectId: 'wrozo-5b147',
    storageBucket: 'wrozo-5b147.firebasestorage.app',
    iosBundleId: 'com.example.wrozo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApzb6y29nD1FszKdzL3akbtLPZEf8DZ_o',
    appId: '1:448205141152:ios:f5625bf9bd7ced23e3c5c5',
    messagingSenderId: '448205141152',
    projectId: 'wrozo-5b147',
    storageBucket: 'wrozo-5b147.firebasestorage.app',
    iosBundleId: 'com.example.wrozo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCLZSfvpt6II5GhX7LqWO-YCkA5WgzFKA',
    appId: '1:448205141152:web:7560ae6c33d5297ee3c5c5',
    messagingSenderId: '448205141152',
    projectId: 'wrozo-5b147',
    authDomain: 'wrozo-5b147.firebaseapp.com',
    storageBucket: 'wrozo-5b147.firebasestorage.app',
  );
}
